version: '1.0'  # Use a more recent version of Compose

services:
  zkp_server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "1337:1337"  # Expose port 1337 for external access
    environment:
      NTL_VERSION: 11.4.1

  zkp_client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./data/client_output.txt:/ZKP_client/data/waiting_time.txt
    network_mode: service:zkp_server
